# Use this to create env:
# conda env create --file environment.yml

# Use this to update env:
# conda env update --file environment.yml --prune
name: db_web_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - psycopg2
  - sqlalchemy
  - pandas
  - flask
  - ipykernel
  - openpyxl
  - lxml
  - Flask-WTF
  - html5lib
  - xlrd
  - jupyter
  - matplotlib
  - pip
  - ipympl
  - jupyterlab
  - paramiko
  - seaborn
  - notebook
  - plotly=5
  - rise
  - pywin32
  - pip:
    - pretty_html_table
    - jupyterlab
    - pillow