# Use this to create env:
# conda env create --file environment.yml

# Use this to update env:
# conda env update --file environment.yml --prune
name: db_web_app
dependencies:
  - python=3.11
  - psycopg2
  - sqlalchemy
  - pandas
  - flask
  - ipykernel
  - openpyxl
  - lxml
  - gunicorn
  - pip
  - pip:
    - pretty_html_table