# Use this to create env:
# conda env create --file environment.yml

# Use this to update env:
# conda env update --file environment.yml --prune
name: coordinate_cleaner_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - geopandas=1.0
  - sqlalchemy=2.0
  - matplotlib
  - folium
  - shapely
  - openpyxl
  - psycopg2

