import constants
import utils.queries as q

def drop_auto_generated_columns(dataframe):
    '''
    Drops any columns generated by a Python script or the database. If 'ignore', suppress error and only existing labels are dropped.
    '''
    dataframe = dataframe.drop(columns=constants.AUTO_GENERATED_COLUMNS, errors="ignore")

    return dataframe

def match_column_positions(upload_file_df, db_data_df):
    '''
    Tries to rearrange the column positions of upload_file to match db_data. 
    If number of columns or column names differ an exception gets raised.
    '''
  
    if len(upload_file_df.columns) == len(db_data_df.columns):
        try:
            upload_file_df = upload_file_df[db_data_df.columns]
        except KeyError as e:
            raise Exception(f"The following columns where found in the database base table but not in the upload file: {e.args[0]}")
    else:
        raise Exception(f"Number of columns in database table does match number of columns in upload file. Columns found database: {db_data_df.columns}. Columns found in upload file: {upload_file_df.columns}")
    return upload_file_df