from db_names import get_sheet_rename_map
import os
import constants.db_table_related_constants as db_table_related_constants
from utils import queries
import constants.misc_constants as misc_constants
import utils.queries as q
import json
import requests

def drop_auto_generated_columns(dataframe):
    '''
    Drops any columns generated by a Python script or the database. If 'ignore', suppress error and only existing labels are dropped.
    '''
    dataframe = dataframe.drop(columns=misc_constants.AUTO_GENERATED_COLUMNS, errors="ignore")

    return dataframe

def match_column_positions(upload_file_df, db_data_df):
    '''
    Tries to rearrange the column positions of upload_file to match db_data. 
    If number of columns or column names differ an exception gets raised.
    '''
    
  
    if len(upload_file_df.columns) == len(db_data_df.columns):
        try:
            upload_file_df = upload_file_df[db_data_df.columns]
        except KeyError as e:
            raise Exception(f"The following columns where found in the database table but not in the upload file: {e.args[0]}")
    else:
        raise Exception(f"Number of columns in database table does match number of columns in upload file. Columns found database: {db_data_df.columns}. Columns found in upload file: {upload_file_df.columns}")
    return upload_file_df

def get_db_generated_uuid_col(table_name, schema_name):
    table_info_df = queries.get_table_information(table_name, schema_name=schema_name)
    db_generated_uuid = table_info_df[table_info_df["column_default"] == 'gen_random_uuid()']["column_name"]

    if len(db_generated_uuid) < 0 or len(db_generated_uuid) > 1:
        raise Exception(f"Found {len(db_generated_uuid)} db generated uuid in {table_name}, but expects 0 or 1") 
    elif len(db_generated_uuid) == 1:
        db_generated_uuid = db_generated_uuid.iloc[0]
    else:
        pass
    return db_generated_uuid

def empty_folder(folder_path, exclude=[]):
    # Check if the folder exists
    if not os.path.exists(folder_path):
        print(f"Folder '{folder_path}' does not exist.")
        return
    
    # Iterate over the files and directories in the folder
    for item in os.listdir(folder_path):
        item_path = os.path.join(folder_path, item)
        
        # Check if it's a file or directory
        if os.path.isfile(item_path) and item not in exclude:
            # Remove the file
            os.remove(item_path)
            print(f"Removed file: {item_path}")
        elif os.path.isdir(item_path):
            # Remove the directory recursively
            empty_folder(item_path)
            # Remove the empty directory
            os.rmdir(item_path)
            print(f"Removed directory: {item_path}")
            
def load_json_url(url):
# The URL of the JSON file

    try:
        # Send an HTTP GET request to the URL
        response = requests.get(url)
        # Check if the request was successful (status code 200)
        response.raise_for_status()

        # Parse the JSON content
        json_data = response.json()

        # Print the JSON content (or do something else with it)
        return json_data

    except requests.exceptions.RequestException as e:
        # Handle any errors that occur during the HTTP request
        print(f"HTTP request failed: {e}")

    except json.JSONDecodeError as e:
        # Handle JSON decoding errors
        print(f"Failed to parse JSON: {e}")

def values_and_keys_to_lower(d):
    '''
    Makes all keys and values of a dictionary (nested or not nested) lower case
    '''
    if isinstance(d, dict):
        return {values_and_keys_to_lower(k): values_and_keys_to_lower(v) for k, v in d.items()}
    elif isinstance(d, list):
        return [values_and_keys_to_lower(i) for i in d]
    elif isinstance(d, str):
        return d.lower()
    else:
        return d
        


def extract_leaf_values_from_dict(dictionary):
    for value in dictionary.values():
        if isinstance(value, dict):
            yield from extract_leaf_values_from_dict(value)
        else:
            yield value
            