from constants import DATABASE_CONFIG, DATABASE_CONFIG_2, ENGINE
import pandas as pd
import psycopg2

 
 
def get_table_names(schema_name, database_name):
    q = f'''    
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = '{schema_name}' and table_catalog = '{database_name}'
    '''
    df = pd.read_sql(sql=q, con=ENGINE)
    return df['table_name']

def get_primary_key(table_name, schema_name, database_name):
    q = f'''
    SELECT 
    column_name
    FROM 
        information_schema.table_constraints AS tc
    JOIN 
        information_schema.key_column_usage AS kcu 
        ON tc.constraint_name = kcu.constraint_name
    WHERE 
        tc.constraint_type = 'PRIMARY KEY' 
        and tc.table_name = '{table_name}'
        and tc.table_schema = '{schema_name}'
        and tc.table_catalog = '{database_name}'
    '''
    df = pd.read_sql_query(q, ENGINE)
    return list(df['column_name'])
    
    

def get_table_information(table_name, schema_name):
    f'''
    Returns a dataframe with the following details about a table:
    
    ['table_catalog', 'table_schema', 'table_name', 'column_name',
       'ordinal_position', 'column_default', 'is_nullable', 'data_type',
       'character_maximum_length', 'character_octet_length',
       'numeric_precision', 'numeric_precision_radix', 'numeric_scale',
       'datetime_precision', 'interval_type', 'interval_precision',
       'character_set_catalog', 'character_set_schema', 'character_set_name',
       'collation_catalog', 'collation_schema', 'collation_name',
       'domain_catalog', 'domain_schema', 'domain_name', 'udt_catalog',
       'udt_schema', 'udt_name', 'scope_catalog', 'scope_schema', 'scope_name',
       'maximum_cardinality', 'dtd_identifier', 'is_self_referencing',
       'is_identity', 'identity_generation', 'identity_start',
       'identity_increment', 'identity_maximum', 'identity_minimum',
       'identity_cycle', 'is_generated', 'generation_expression',
       'is_updatable']
    '''

    column_query = f'''
    SELECT *
    FROM information_schema.columns 
    WHERE table_schema = '{schema_name}' AND table_name = '{table_name}' 
    ORDER BY ordinal_position;
    '''

    df = pd.read_sql_query(column_query, ENGINE)
       
    return df


def get_table_dtypes(table_name, schema_name):
    '''
    Note: this returns all columns, also autogenerated ones.
    '''
    return get_table_information(table_name, schema_name)[['table_name', 'column_name', 'data_type', 'udt_name']]


def get_possible_datatypes(category):
    
    if category == "date":
        code = 'D'
        
    q = f'''
    SELECT typname
    FROM pg_catalog.pg_type
    WHERE typcategory = '{code}';
    '''

    df = pd.read_sql_query(q, ENGINE)
    return list(df['typname'])

